In [1]:
import torch

In [2]:
print(torch.__version__)

1.13.0+cpu


# PyTorch Tensors Ref:  https://pytorch.org/docs/stable/tensors.html

In [50]:
#1. scalar tensor
scalar1 = torch.tensor(7) # scalar is a single number
scalar2 = torch.tensor(3)
scalar1

tensor(7)

In [51]:
scalar1.ndim

0

In [57]:
scalar1.size()

torch.Size([])

In [49]:
#2. vector
vector1 = torch.tensor([1,2])  # vector is a single dimension but can contain many numbers/values
vector2 = torch.tensor([3,2,1])

vector1

tensor([1, 2])

In [52]:
vector1.ndim  

1

In [55]:
vector1.size()

torch.Size([2])

In [138]:
vector2.shape

torch.Size([3])

In [46]:
#3. matrix
matrix1 = torch.tensor([ [1,2],
                         [3,4]  ])

matrix1

tensor([[1, 2],
        [3, 4]])

In [53]:
matrix1.ndim 

2

In [59]:
matrix1.shape

torch.Size([2, 2])

In [58]:
matrix1.size() 

torch.Size([2, 2])

In [67]:
#4. tensor

tensor1 = torch.tensor([[ [1,2,3],
                          [4,5,6],
                       ]])
tensor1

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [68]:
tensor1.ndim 

3

In [69]:
tensor1.shape

torch.Size([1, 2, 3])

# Random tensors

https://pytorch.org/docs/stable/generated/torch.rand.html

In [71]:
#6. create a random tensor of size(3,4)
random_tensor_1 = torch.rand(3,4)
random_tensor_1

tensor([[0.5397, 0.5231, 0.2552, 0.0658],
        [0.1436, 0.0566, 0.6598, 0.2071],
        [0.0296, 0.9643, 0.0966, 0.0531]])

In [111]:
random_tensor_1.ndim

2

In [117]:
# create a random tensor with similar shape to an image tensor
random_image_tensor_2 = torch.rand(size=(224,224,3)) # size = height,width,color
random_image_tensor_2.ndim

3

In [113]:
# creating random tensor like/ref of another tensor using 'rand_like'
random_tensor_3 = torch.rand_like(random_tensor_1)
random_tensor_3

tensor([[0.4810, 0.7743, 0.3176, 0.1044],
        [0.4081, 0.7681, 0.4934, 0.9210],
        [0.7929, 0.9984, 0.3468, 0.3631]])

In [116]:
# creating random tensor with integers with limit

# https://pytorch.org/docs/stable/generated/torch.randint.html

random_int_tensor_4 = torch.randint(1,9,(2,3))  # low=1, high=9, size= (2,3)
random_int_tensor_4

tensor([[1, 5, 3],
        [8, 4, 3]])

In [78]:
# Create a tensor of all zeros
tensor_zero = torch.zeros(3,4)
tensor_zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [79]:
tensor_zero.ndim 

2

In [80]:
# Create a tensor of all ones
tensor_1 = torch.ones(3,4)
tensor_1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [91]:
#Creating a range of tensors  and tensors-like

# tensor_range = torch.range(3,6,1)  # Use torch.arange(), torch.range() is deprecated in future release
tensor_range_1 = torch.arange(1,6)
tensor_range_1

tensor([1, 2, 3, 4, 5])

In [119]:
tensor_range_2 = torch.arange(start=1,end=6,step=1)
tensor_range_2 

tensor([1, 2, 3, 4, 5])

In [93]:
tensor_range_3 = torch.arange(1,8,2)
tensor_range_3

tensor([1, 3, 5, 7])

In [95]:
# Create a range of values 0 to 10
tensor_range_4 = torch.arange(start =1 , end=10 , step=2)
tensor_range_4

tensor([1, 3, 5, 7, 9])

In [97]:
# Can also create a tensor of zeros similar to another tensor
tensor_zero_1 = torch.zeros_like(tensor_zero)
tensor_zero_1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [98]:
tensor_zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [120]:
tensor_like_1 = torch.ones_like(input=tensor_range_4) # ref of another tensor
tensor_like_1

tensor([1, 1, 1, 1, 1])

# Tensor datatypes

Ref: https://pytorch.org/docs/stable/tensors.html

In [140]:
# half precision point =   16 bit: occupies 16 bits (2 bytes) in computer memory
# single precision point = 32 bit : occupies 32 bits in computer memory
# Double precision point = 64 bit : occupies 64 bits in computer memory

#Ref : https://en.wikipedia.org/wiki/Precision_(computer_science)

In [141]:
# NOTE: Tensor datatypes is one of the 3 big errors you will run into with PyTorch & DL:
# 1. Tensors not right datatype
# 2. Tensors not right shape
# 3. Tensors not on the right device


In [129]:
float_32_tensor_1 = torch.tensor( [20.0,12.0,23.0],   
                        dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                        device=None, # What device is your tensor on , default = cpu
                        requires_grad=False # whether or not to track gradients with this tensor operations
                       )

In [130]:
float_32_tensor_1

tensor([20., 12., 23.])

In [133]:
float_32_tensor_1.device  , float_32_tensor_1.dtype ,  float_32_tensor_1.shape

(device(type='cpu'), torch.float32, torch.Size([3]))

In [139]:
float_16_tensor_1 = float_32_tensor_1.type(torch.float16)
float_16_tensor_1

tensor([20., 12., 23.], dtype=torch.float16)

In [142]:
float_16_tensor_1 * float_32_tensor_1

tensor([400., 144., 529.])

In [144]:
int_32_tensor_1 = float_32_tensor_1.type(torch.int32)
int_32_tensor_1

tensor([20, 12, 23], dtype=torch.int32)

In [145]:
float_32_tensor_1 * int_32_tensor_1

tensor([400., 144., 529.])

In [146]:
int_64_tensor_1 = torch.tensor( [2,6,12],
                                device='cpu',
                                dtype=torch.long,
                                requires_grad=False )

In [148]:
mul_tensor_1 = int_64_tensor_1 * float_32_tensor_1

# tensor attributes

In [304]:
# tensor attributes: mul_tensor_1

print(mul_tensor_1)
print(f"data type of tensor: {mul_tensor_1.dtype}")
print(f"shape of the tensor: {mul_tensor_1.size()}")
print(f"device of the tensor: {mul_tensor_1.device}")   # cpu, cuda, mps, cuda:0
print(f"tensor layout: {mul_tensor_1.layout}")  #  represents the memory layout of a tensor


tensor([ 40.,  72., 276.])
data type of tensor: torch.float32
shape of the tensor: torch.Size([3])
device of the tensor: cpu
tensor layout: torch.strided


In [207]:
#creating tensors
tensor_9 = torch.tensor ([[
                            [7,8],
                            [9,10],
                            [11,12]
                                 ]])
tensor_10 = torch.tensor([[
                            [1,2,3],
                            [4,5,6]
                                ]])


# tensor operations (manipulating tensors)

tensor operations include:

Addition

Subtraction

Multiplication (element-wise)

Division

Matrix multiplication

In [171]:
# addition
tensor_4 = torch.tensor( [10,12,13] )

tensor_4 + 10

tensor([20, 22, 23])

In [170]:
tensor_5 = tensor_4 + tensor_3
tensor_5

tensor([30, 24, 36])

In [173]:
tensor_6 = torch.tensor( [[
                            [1,2,3,4],
                            [3,4,5,6]
                                ]] )
tensor_6  

tensor([[[1, 2, 3, 4],
         [3, 4, 5, 6]]])

In [179]:
tensor_5.size()    , tensor_5.shape 

(torch.Size([3]), torch.Size([3]))

In [180]:
tensor_6.size()  , tensor_6.shape

(torch.Size([1, 2, 4]), torch.Size([1, 2, 4]))

In [191]:
tensor_5 + tensor_6  # here both are in diff shape. so, getting below error

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 2

In [188]:
# subtraction 

tensor_7 = tensor_5 - tensor_4
tensor_7

tensor([20, 12, 23])

In [189]:
tensor_8 = tensor_4 - tensor_5
tensor_8

tensor([-20, -12, -23])

In [190]:
tensor_7 - 2

tensor([18, 10, 21])

In [192]:
# Multiplication (element wise)

tensor_7 * 2

tensor([40, 24, 46])

In [206]:
tensor_4 * tensor_4 

tensor([100, 144, 169])

# Matrix multiplication rules:

1. inner dimensions must match

Ex:  (3,2) @ (3,2) --> won't work

      (3,2) @ (2,3) --> will work
     
     
     (2,3) @ (3,2) --> will work
     
2. the resulting matrix has the shape of the outer dimensions

Ex:        (3,2) @ (2,3) --> (3,3)

        (2,3) @ (3,2) --> (2,2)

In [216]:
torch.matmul(torch.rand(3,2) , torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [218]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[1.2954, 0.2767, 0.4689],
        [0.4397, 0.2149, 0.3617],
        [0.8060, 0.1964, 0.3323]])

In [215]:
# Matrix Multiplication (important in DL) 
torch.matmul(tensor_4 , tensor_4)    # here tensor is a vector. thats why getting this result

tensor(413)

In [214]:
torch.matmul(tensor_10 ,tensor_9)   # here tensor_9 , tensor_10 are matrix

# always prefer this approach for matrix multiplication in PyTorch. because it takes less time for multiplication

tensor([[[ 58,  64],
         [139, 154]]])

In [221]:
tensor_10.shape 

torch.Size([1, 2, 3])

In [222]:
torch.matmul(tensor_10 , tensor_10) # getting error becoz inner dimensions are not matching (2,3) @ (2,3)

RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [1, 3] but got: [1, 2].

In [223]:
# torch.mm() is same as torch.matmul() , .mm() is alias/code_short_cut of .matmul()

# Finding the min, max,sum,mean.. (tensor aggregations)

In [243]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [246]:
x.min()  , torch.min(x)

(tensor(0), tensor(0))

In [248]:
x.max()   , torch.max(x) 

(tensor(90), tensor(90))

In [250]:
x.mean(dtype=torch.float32)  

tensor(45.)

In [252]:
torch.mean(x , dtype=torch.float32) 

tensor(45.)

In [253]:
x.sum() 

tensor(450)

In [254]:
torch.sum(x) 

tensor(450)

In [261]:
print(f"min of tensor: {torch.min(x)}")
print(f"max of tensor: {torch.max(x)}")
print(f"mean of tensor: {torch.mean(x,dtype=torch.float16)}") 
print(f"sum of tensor: {torch.sum(x)}") 

min of tensor: 0
max of tensor: 90
mean of tensor: 45.0
sum of tensor: 450


# positional min/max

In [266]:
# finding the positional min (position of the minimum number) in the above tensor

torch.argmin(x) 

torch.argmax(x)

print(f"minimum number position in the tensor: {torch.argmin(x)}" )
print(f"maxmimum number position in the tensor: {torch.argmax(x)}" )

minimum number position in the tensor: 0
maxmimum number position in the tensor: 9


# changing tensor data type

In [268]:
tensor_12 = torch.arange(11,18,2)
tensor_12.dtype

torch.int64

In [272]:
dtype_change_tensor_1 = tensor_12.type(dtype=torch.float16)
dtype_change_tensor_1
dtype_change_tensor_1.dtype

torch.float16

In [274]:
tensor_9.dtype

torch.int64

In [273]:
dtype_change_tensor_2 = tensor_9.type(dtype=torch.float16)
dtype_change_tensor_2

tensor([[[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]], dtype=torch.float16)

# reshaping, stacking, squeezing and unsqueezing

reshaping - reshapes an input tensor to a defined shape

Stacking: combine multiple tensors on top of each other (vstack) or side by side 

          :
          
          

In [279]:
# reshaping - reshapes an input tensor to a defined shape
tensor_12    , tensor_12.shape 

(tensor([11, 13, 15, 17]), torch.Size([4]))

In [282]:
# adding an extra dimension to tensor_12
tensor_12_reshaped_1 = tensor_12.reshape(1,4)
tensor_12_reshaped_1  , tensor_12_reshaped_1.shape

(tensor([[11, 13, 15, 17]]), torch.Size([1, 4]))

In [285]:
tensor_12_reshaped_2 = tensor_12.reshape(2,2)

tensor_12_reshaped_2  , tensor_12_reshaped_2.shape

(tensor([[11, 13],
         [15, 17]]),
 torch.Size([2, 2]))

In [287]:
tensor_12_reshaped_3 = tensor_12.reshape(1,2,2)
tensor_12_reshaped_3  , tensor_12_reshaped_3

(tensor([[[11, 13],
          [15, 17]]]),
 tensor([[[11, 13],
          [15, 17]]]))

In [289]:
tensor_12_reshaped_4 = tensor_12.reshape(2,1,2)
tensor_12_reshaped_4   , tensor_12_reshaped_4.shape

(tensor([[[11, 13]],
 
         [[15, 17]]]),
 torch.Size([2, 1, 2]))

In [291]:
tensor_12_reshaped_5 = tensor_12.reshape(2,2,1)
tensor_12_reshaped_5   , tensor_12_reshaped_5.shape 

(tensor([[[11],
          [13]],
 
         [[15],
          [17]]]),
 torch.Size([2, 2, 1]))

# view: 

torch.Tensor.view(shape) :::: Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

In [294]:
tensor_12_view_1 = tensor_12.view(1,4)
tensor_12_view_1

tensor([[11, 13, 15, 17]])

In [296]:
tensor_12_view_2 = tensor_12.view(2,2,1)
tensor_12_view_2

tensor([[[11],
         [13]],

        [[15],
         [17]]])

# Stack

In [275]:
#Stacking : Concatenates a sequence of tensors along a new dimension

# combine multiple tensors on top of each other (vstack) or side by side (hstack)




In [276]:
#squeeze : removes all '1' dimensions from a tensor

#unsqueeze : add a '1' dimension to a target tensor

# Excersise -1

1. create a random tensor with shape(7,7)

2. perform matrix multiplication on the tensor from 1 with another random tensor with shape(1,7)

3. set the random seed to 0 and do 1&2 over again.

In [299]:
tensor_A = torch.rand(7,7)
tensor_A 

tensor([[0.4839, 0.3076, 0.9203, 0.4500, 0.3404, 0.6884, 0.3000],
        [0.0357, 0.9424, 0.9006, 0.1285, 0.7029, 0.7399, 0.6008],
        [0.3692, 0.2854, 0.4239, 0.9397, 0.9875, 0.5138, 0.3223],
        [0.9233, 0.0758, 0.3009, 0.7264, 0.2362, 0.3807, 0.1793],
        [0.6342, 0.3813, 0.4319, 0.6552, 0.8297, 0.8372, 0.0288],
        [0.5026, 0.4374, 0.8455, 0.5692, 0.3020, 0.3397, 0.4205],
        [0.8214, 0.5231, 0.2453, 0.2346, 0.2925, 0.1382, 0.1452]])

In [300]:
tensor_B = torch.rand(1,7)
tensor_B 

tensor([[0.5533, 0.9961, 0.1985, 0.4972, 0.1499, 0.3794, 0.7071]])

In [302]:
tensor_B_transpose = tensor_B.T
tensor_B_transpose.shape 

torch.Size([7, 1])

In [303]:
torch.matmul(tensor_A , tensor_B_transpose)


tensor([[1.5049],
        [2.0120],
        [1.6108],
        [1.3138],
        [1.6044],
        [1.6361],
        [1.3398]])

In [305]:
# # Set the random seed
RANDOM_SEED=0 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_seed_tensor_A = torch.rand(7,7)
random_seed_tensor_A

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [306]:
random_seed_tensor_B = torch.rand(1,7)
random_seed_tensor_B

tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

In [307]:
random_seed_tensor_B_transpose = random_seed_tensor_B.T

In [308]:
torch.mm(random_seed_tensor_A , random_seed_tensor_B_transpose)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

# Reference:

https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb