In [5]:
import tensorflow as tf
#import tensorflow_addons as tfa
import tensorflow_probability as tfp

import numpy as np

In [3]:
print(tf.__version__)

#print(tfa.__version__)

print(tfp.__version__)

2.12.0
0.19.0


# creating tensor with tf.constant()

In [6]:
#lets create tensor with tf.constant()

scalar = tf.constant(7)  # here scalar is a number
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
scalar.ndim  # Rank / No.of dimensions   # scaler has rank 0 , vector -1 , matrix-2 , tensor - n

0

In [10]:
#create a vector with 1 dimension
vector = tf.constant([1,2,3])  # vector is a number with direction
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [11]:
vector.ndim

1

In [14]:
#create a matrix more than 2 dimension
matrix = tf.constant([[1,2],
                     [4,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 3]])>

In [15]:
matrix.ndim

2

In [22]:
#create a matrix more than 3 dimension
matrix1 = tf.constant([[1,2,3,4],
                     [4,3,3,1],
                     [3,4,3,1]])
matrix1

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [4, 3, 3, 1],
       [3, 4, 3, 1]])>

In [23]:
matrix1.ndim

2

In [26]:
#matrix with defined data type
matrix2 = tf.constant([1,2,2] , dtype=tf.float16)

matrix2

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 2., 2.], dtype=float16)>

# creating tensor with tf.variable

In [35]:
#create the tensor with tf.constant() & tf.variable()
changeble_tensor = tf.Variable([10,7])  # can assign new val
unchangeble_tensor = tf.constant([3,7])  # we can't assign new val to constant tensor

changeble_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>

In [36]:
unchangeble_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7])>

In [37]:
changeble_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [39]:
changeble_tensor[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 7])>

In [41]:
changeble_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [42]:
unchangeble_tensor[0].assign(8)  # can assign new value

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# creating random tensors

In [48]:
random1 = tf.random.Generator.from_seed(42)

random1 = random1.normal(shape=(2,3))

random1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [3]:
#shuffle the tensor

not_shuffled = tf.constant([[1,2,3,4],
                           [2,3,1,4]])
not_shuffled

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 3, 1, 4]])>

In [53]:
# shuffle our non shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 3, 1, 4],
       [1, 2, 3, 4]])>

In [7]:
#  https://www.tensorflow.org/api_docs/python/tf/random/set_seed
# 4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.
# If we want our shuffled tensors to be in the same order, we have to use the global level random seed as well as the operation level seed:
tf.random.set_seed(23) # global level seed
tf.random.shuffle(not_shuffled , seed=42) # operational level seed

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 3, 1, 4],
       [1, 2, 3, 4]])>

# Other ways to make Tensors

In [8]:
#create a tensor of all ones
tf.ones([2,4])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [10]:
#create a tensor of all zeros

#tf.zeros([2,4])

tf.zeros(shape=(2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# turning numPy arrays into tensors
the main diff b/w numPy arrays and TensorFlow Tensors is that tensors can run on GPU(much faster for numerical computing)



In [22]:
import numpy as np

numpy_A = np.arange(1,25,dtype = np.int16)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [23]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(24,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)>

In [41]:
tensor_B = tf.constant(numpy_A , shape=(4,3,2))  # 4*3*2  / 2*3*4 / 2*12 / 2*6*2 / 1*6*4
tensor_B

<tf.Tensor: shape=(4, 3, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int16)>

In [42]:
tensor_B.ndim    


3

# Getting information from tensors
   shape, axis, rank, size

In [43]:
tensor_B.shape

TensorShape([4, 3, 2])

In [44]:
tensor_B.ndim # rank or dimension

3

In [45]:
tf.size(tensor_B)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [46]:
tensor_B[0]

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)>

In [50]:
print('Datatype of every element:',tensor_B.dtype)
print('No.of dimensions (Rank):' , tensor_B.ndim)
print('Shape of tensor:' , tensor_B.shape)
print('Elements along the 0 axis:', tensor_B.shape[0])
print('Elements along the last axis:',tensor_B.shape[-1])
print('Total number of elements in our tensor:',tf.size(tensor_B))
print('Total number of elements in our tensor:',tf.size(tensor_B).numpy())

Datatype of every element: <dtype: 'int16'>
No.of dimensions (Rank): 3
Shape of tensor: (4, 3, 2)
Elements along the 0 axis: 4
Elements along the last axis: 2
Total number of elements in our tensor: tf.Tensor(24, shape=(), dtype=int32)
Total number of elements in our tensor: 24


# indexing tensors
   tensors can indexed just like python lists

In [52]:
tensor_B[:2,:2,:2]  # get the first two elements of each dimension

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 7,  8],
        [ 9, 10]]], dtype=int16)>

In [54]:
#get the first element from  each dimension from each index except the last one
tensor_B[:,:,:-1]

<tf.Tensor: shape=(4, 3, 1), dtype=int16, numpy=
array([[[ 1],
        [ 3],
        [ 5]],

       [[ 7],
        [ 9],
        [11]],

       [[13],
        [15],
        [17]],

       [[19],
        [21],
        [23]]], dtype=int16)>

In [68]:
#create a rank 2 tensor

rank_2_tensor = tf.constant([[2,3],
                            [4,5]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [63]:
#get the last item of each row in above tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5])>

In [67]:
# Add an extra dimension to the above rank 2 tensor

rank_3_tensor = rank_2_tensor[... , tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]])>

In [71]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor , axis=-1)  # -1 means expands the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]])>

In [72]:
#expand the 0 axis

tf.expand_dims(rank_2_tensor , axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [4, 5]]])>

In [74]:
#expand the 1 axis
tf.expand_dims(rank_2_tensor , axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[2, 3]],

       [[4, 5]]])>

# manuplating tensor (tensor operations)

Basic operations:     + , - , * , /

In [75]:
tensor = tf.constant([[10,7],
                     [3,7]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  7]])>

In [76]:
tensor + 10   # Addition

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 17]])>

In [77]:
tensor * 10   #multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  70]])>

In [78]:
tensor-9 # subtraction

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1, -2],
       [-6, -2]])>

In [80]:
tensor / 2  # division

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 3.5]])>

In [81]:
# tensorFlow built-in methods for basic operations

tf.add(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 17]])>

In [83]:
tf.multiply(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  70]])>

In [82]:
tf.subtract(tensor , 9)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1, -2],
       [-6, -2]])>

In [84]:
tf.divide(tensor , 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 3.5]])>

# matrix multiplication

In ML, matrix multiplication is one of the common tensor operation

There are 2 rules our tensors(or matrices) need to fulfill, if we're going to matrix multiplication:

1. The inner dimensions must match
2. The resulting matrix has the shape of the inner dimensions

http://matrixmultiplication.xyz/

https://www.tensorflow.org/api_docs/python/tf/linalg/matmul

In [85]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  7]], shape=(2, 2), dtype=int32)


In [88]:
#matrix multiplication in tensorFlow
tf.matmul(tensor , tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121, 119],
       [ 51,  70]])>

In [89]:
# matrix multiplication with python operator '@'

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121, 119],
       [ 51,  70]])>

In [90]:
tensor * tensor   # this is wrong approach

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  49]])>

In [96]:
# create tensor1 with shape(3,3) & tensor2 with shape (3,2)

tensor_1 = tf.constant([ [1,2,3],
                         [2,3,4],
                         [3,4,5] ])

tensor_2 = tf.constant([ [2,3],
                         [3,4],
                         [4,5] ])

tensor_1.shape , tensor_2.shape

tf.matmul(tensor_1,tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 26],
       [29, 38],
       [38, 50]])>

In [101]:
tf.reshape(tensor_2 , shape=(2,3,1))

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[2],
        [3],
        [3]],

       [[4],
        [4],
        [5]]])>

In [102]:
tensor_1 @ tf.reshape(tensor_2,shape=(2,3,1))  # tensor matrix multiplication

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[17],
        [25],
        [33]],

       [[27],
        [40],
        [53]]])>

In [103]:
tf.matmul(tensor_1, tf.reshape(tensor_2 , shape=(2,3,1)))

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[17],
        [25],
        [33]],

       [[27],
        [40],
        [53]]])>

In [104]:
# matrix transpose
tf.transpose(tensor_1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])>

In [109]:
tf.matmul(tensor_1 , tf.reshape(tensor_2,shape=(2,3,1)))

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[17],
        [25],
        [33]],

       [[27],
        [40],
        [53]]])>

# Matrix multiplication is also referred to as the dot product.

you can perform matrix multiplication using:

tf.matmul()

tf.tensordot()

https://www.tensorflow.org/api_docs/python/tf/tensordot#:~:text=Tensordot%20(also%20known%20as%20tensor,is%20equivalent%20to%20matrix%20multiplication.

In [111]:
tf.tensordot(tensor_1 , tensor_2 , axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 26],
       [29, 38],
       [38, 50]])>

#  Matrix multiplication Note

Generally,when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose(rather than reshape) one of the tensor to get satisfy matrix multiplication rule.

# changing tensor data type

In [116]:

#  https://www.tensorflow.org/guide/mixed_precision

tensor_3 = tf.constant([2.2,3.2,4.0])  # models use the float32 dtype, which takes 32 bits of memory. 
tensor_3.dtype

tensor_3 = tf.cast(tensor_3 , dtype= tf.float16) # float16 and bfloat16, each which take 16 bits of memory instead
tensor_3

#Modern accelerators can run operations faster in the 16-bit dtypes, as they have specialized hardware to run 16-bit computations and 16-bit dtypes can be read from memory faster.

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([2.2, 3.2, 4. ], dtype=float16)>

In [118]:
tensor_4 = tf.constant([2,4])
tensor_4.dtype

# changing dtype of int32 to float16

tensor_4 = tf.cast(tensor_4 , dtype= tf.float16)
tensor_4.dtype

tf.float16

# Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [119]:
tensor_5 = tf.constant([-7,-9])
tensor_5

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, -9])>

In [120]:
# get the absolute value

tf.abs(tensor_5)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9])>

# Let's go through the following forms of aggregation:

Get the minimum

Get the maximum

Get the mean of a tensor

Get the sum of a tensor


In [6]:
# create a random tensor with the values between 0 and 100 with size 50

random_tensor_1 = tf.constant(np.random.randint(0,100 ,size=50))
random_tensor_1

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([24, 73, 30, 72, 79, 76, 56,  7, 28,  3, 46, 56, 17, 46, 84, 27, 73,
       54, 23, 15, 15, 37,  6, 26, 75, 12, 37, 77, 32, 18, 28, 16, 36, 84,
       51,  2, 51, 74, 86, 27, 81, 39, 93, 59, 49, 64, 65, 92, 22, 48])>

In [127]:
tf.shape(random_tensor_1)  , random_tensor_1.shape  , random_tensor_1.ndim

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([50])>, TensorShape([50]), 1)

In [128]:
# find the minimum
tf.reduce_min(random_tensor_1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [129]:
# find the maximum
tf.reduce_max(random_tensor_1)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [130]:
# find the mean of a tensor
tf.reduce_mean(random_tensor_1)

<tf.Tensor: shape=(), dtype=int32, numpy=52>

In [131]:
#find the sum of a tensor

tf.reduce_sum(random_tensor_1)

<tf.Tensor: shape=(), dtype=int32, numpy=2606>

In [132]:
tf.reduce_prod(random_tensor_1)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [134]:
random_tensor_1

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([63, 79, 95, 58, 79, 61, 85,  1, 30, 17, 92, 74, 51, 32, 81, 15, 79,
       88, 46, 57, 32, 58, 70, 29, 24, 71, 66, 56, 25,  7, 52, 30, 53, 97,
       62, 40, 15, 93, 79, 69, 39, 78, 41, 19, 43, 50, 48, 20, 19, 38])>

In [13]:
# find the variance of a tensor

# https://www.tensorflow.org/probability/api_docs/python/tfp/stats/variance

tf.math.reduce_variance(tf.cast(random_tensor_1 , dtype=tf.float32))

tfp.stats.variance(random_tensor_1)

<tf.Tensor: shape=(), dtype=float32, numpy=691.1476>

In [17]:
# find the standard variance of a tensor

tensor_6 = tf.random.normal(shape=(100,2,3))

tf.math.reduce_std(tf.cast(random_tensor_1 , dtype= tf.float32))

#tfp.stats.stddev(tensor_6)

<tf.Tensor: shape=(), dtype=float32, numpy=26.289686>

# Find the positional Minimum and Maximum

In [20]:
tensor_7 = tf.random.uniform(shape=[50])

tensor_7

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.41821814, 0.8851683 , 0.22972286, 0.95261645, 0.00649953,
       0.77357376, 0.8214545 , 0.573673  , 0.1333561 , 0.3601544 ,
       0.43876314, 0.975327  , 0.99357545, 0.89346254, 0.22383165,
       0.16433656, 0.6880901 , 0.36315453, 0.01203835, 0.69435513,
       0.2423842 , 0.57816565, 0.050524  , 0.56450534, 0.48467195,
       0.89573073, 0.8530854 , 0.43903565, 0.27312076, 0.39780796,
       0.14325964, 0.8905915 , 0.46033573, 0.79400754, 0.8357674 ,
       0.1267842 , 0.62312126, 0.28557754, 0.37455547, 0.6385808 ,
       0.5814065 , 0.8142139 , 0.9333322 , 0.8590255 , 0.07352245,
       0.4363153 , 0.8062762 , 0.16935265, 0.94184196, 0.0899446 ],
      dtype=float32)>